/**
 * Rendering helpers: turn a Findings report + RemediationResult into console
 * lines and a Markdown PR body. Pure string building — no I/O, no styling
 * dependency (the orchestrator applies colors).
 */

const PR_TITLE = "security: remove PolinRider malware artifacts";

/** Plain lines describing what the scanner found (for console output). */
export function findingLines(findings) {
  return findings.findings.map((f) => {
    const tag = f.contentConfirmed ? "[confirmed]" : "[review]";
    return `${tag} ${f.file}: ${f.description}`;
  });
}

/** Plain lines describing what remediation did (or would do). */
export function resultLines(result) {
  const verb = result.dryRun ? "would " : "";
  const lines = [];
  for (const f of result.applied) {
    lines.push(`${verb}fixed ${f.file}: ${f.description ?? f.action}`);
  }
  for (const n of result.notes) lines.push(n);
  for (const s of result.skipped) {
    lines.push(`skipped ${s.finding.file}: ${s.reason}`);
  }
  return lines;
}

/**
 * Build a Markdown PR body that lists exactly what changed, plus a manual-review
 * section. Replaces the old static PR_BODY so reviewers see a precise diff.
 */
export function buildPrBody({ findings, result }) {
  const out = [];
  out.push("## PolinRider malware cleanup");
  out.push("");
  out.push(
    "Automatically generated by polinrider-remover. Every change below was confirmed by a known PolinRider signature. The scanner reads files as inert text and never executes them.",
  );
  out.push("");

  const fixed = [];
  for (const f of result.applied) {
    const what = result.filesDeleted.includes(f.file) ? "removed" : "cleaned";
    fixed.push(`- \`${f.file}\`: ${what} — ${f.description ?? f.action}`);
  }
  for (const n of result.notes) fixed.push(`- ${n}`);

  if (fixed.length) {
    out.push("### Removed / fixed");
    out.push(...fixed);
    out.push("");
  }

  const review = [
    ...findings.manualReview.map((m) => `- ${m}`),
    ...result.skipped.map((s) => `- \`${s.finding.file}\`: ${s.reason}`),
  ];
  if (review.length) {
    out.push("### Needs manual review");
    out.push(...review);
    out.push("");
  }

  out.push(
    "> ⚠️ Also check the affected developer's machine for the initial dropper (a malicious npm global package or VS Code extension), and rotate any secrets that may have been exposed via committed `.env` files.",
  );
  out.push("");
  return out.join("\n");
}

export { PR_TITLE };
